# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(4095, 830)
        MainWindow.setMinimumSize(QtCore.QSize(300, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background:rgb(91,90,90);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toodle = QtWidgets.QFrame(self.frame_top)
        self.frame_toodle.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_toodle.setMaximumSize(QtCore.QSize(80, 55))
        self.frame_toodle.setStyleSheet("background:rgb(0,143,150);")
        self.frame_toodle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toodle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_toodle.setObjectName("frame_toodle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_toodle)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toodle = QtWidgets.QPushButton(self.frame_toodle)
        self.toodle.setMinimumSize(QtCore.QSize(80, 55))
        self.toodle.setMaximumSize(QtCore.QSize(80, 55))
        self.toodle.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,178,178);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.toodle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("exe/icons/1x/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toodle.setIcon(icon)
        self.toodle.setIconSize(QtCore.QSize(22, 12))
        self.toodle.setFlat(True)
        self.toodle.setObjectName("toodle")
        self.horizontalLayout_3.addWidget(self.toodle)
        self.horizontalLayout.addWidget(self.frame_toodle)
        self.frame_top_east = QtWidgets.QFrame(self.frame_top)
        self.frame_top_east.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top_east.setStyleSheet("background:rgb(51,51,51);")
        self.frame_top_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_east.setObjectName("frame_top_east")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_east)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_appname = QtWidgets.QFrame(self.frame_top_east)
        self.frame_appname.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_appname.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_appname.setObjectName("frame_appname")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_appname)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lab_appname = QtWidgets.QLabel(self.frame_appname)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        self.lab_appname.setFont(font)
        self.lab_appname.setStyleSheet("color:rgb(255,255,255);")
        self.lab_appname.setObjectName("lab_appname")
        self.horizontalLayout_10.addWidget(self.lab_appname)
        self.horizontalLayout_4.addWidget(self.frame_appname)
        self.frame_user = QtWidgets.QFrame(self.frame_top_east)
        self.frame_user.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_user.setObjectName("frame_user")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_user)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lab_user = QtWidgets.QLabel(self.frame_user)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        self.lab_user.setFont(font)
        self.lab_user.setStyleSheet("color:rgb(255,255,255);")
        self.lab_user.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_user.setObjectName("lab_user")
        self.horizontalLayout_9.addWidget(self.lab_user)
        self.horizontalLayout_4.addWidget(self.frame_user)
        self.frame_person = QtWidgets.QFrame(self.frame_top_east)
        self.frame_person.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_person.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_person.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_person.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_person.setObjectName("frame_person")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_person)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lab_person = QtWidgets.QLabel(self.frame_person)
        self.lab_person.setMaximumSize(QtCore.QSize(55, 55))
        self.lab_person.setText("")
        self.lab_person.setPixmap(QtGui.QPixmap("exe/icons/1x/peple.png"))
        self.lab_person.setScaledContents(False)
        self.lab_person.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_person.setObjectName("lab_person")
        self.horizontalLayout_8.addWidget(self.lab_person)
        self.horizontalLayout_4.addWidget(self.frame_person)
        self.frame_min = QtWidgets.QFrame(self.frame_top_east)
        self.frame_min.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_min.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_min.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_min.setObjectName("frame_min")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_min)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bn_min = QtWidgets.QPushButton(self.frame_min)
        self.bn_min.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_min.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("exe/icons/1x/hideAsset 53.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_min.setIcon(icon1)
        self.bn_min.setIconSize(QtCore.QSize(22, 22))
        self.bn_min.setFlat(True)
        self.bn_min.setObjectName("bn_min")
        self.horizontalLayout_7.addWidget(self.bn_min)
        self.horizontalLayout_4.addWidget(self.frame_min)
        self.frame_max = QtWidgets.QFrame(self.frame_top_east)
        self.frame_max.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_max.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_max.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_max.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_max.setObjectName("frame_max")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_max)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bn_max = QtWidgets.QPushButton(self.frame_max)
        self.bn_max.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_max.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_max.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("exe/icons/1x/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_max.setIcon(icon2)
        self.bn_max.setIconSize(QtCore.QSize(22, 22))
        self.bn_max.setFlat(True)
        self.bn_max.setObjectName("bn_max")
        self.horizontalLayout_6.addWidget(self.bn_max)
        self.horizontalLayout_4.addWidget(self.frame_max)
        self.frame_close = QtWidgets.QFrame(self.frame_top_east)
        self.frame_close.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_close.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_close.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bn_close = QtWidgets.QPushButton(self.frame_close)
        self.bn_close.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("exe/icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close.setIcon(icon3)
        self.bn_close.setIconSize(QtCore.QSize(22, 22))
        self.bn_close.setFlat(True)
        self.bn_close.setObjectName("bn_close")
        self.horizontalLayout_5.addWidget(self.bn_close)
        self.horizontalLayout_4.addWidget(self.frame_close)
        self.horizontalLayout.addWidget(self.frame_top_east)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_bottom_west = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_west.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_bottom_west.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_bottom_west.setStyleSheet("background:rgb(51,51,51);")
        self.frame_bottom_west.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_west.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_west.setObjectName("frame_bottom_west")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom_west)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_home = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_home.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_home.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_home.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_home.setObjectName("frame_home")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_home)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bn_home = QtWidgets.QPushButton(self.frame_home)
        self.bn_home.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_home.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_home.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_home.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("exe/icons/1x/icons8-home-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_home.setIcon(icon4)
        self.bn_home.setIconSize(QtCore.QSize(22, 22))
        self.bn_home.setFlat(True)
        self.bn_home.setObjectName("bn_home")
        self.horizontalLayout_15.addWidget(self.bn_home)
        self.verticalLayout_3.addWidget(self.frame_home)
        self.frame_booking = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_booking.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_booking.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_booking.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_booking.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_booking.setObjectName("frame_booking")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_booking)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bn_booking = QtWidgets.QPushButton(self.frame_booking)
        self.bn_booking.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_booking.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_booking.setToolTipDuration(-5)
        self.bn_booking.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_booking.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("exe/icons/1x/icons8-book-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_booking.setIcon(icon5)
        self.bn_booking.setIconSize(QtCore.QSize(22, 22))
        self.bn_booking.setFlat(True)
        self.bn_booking.setObjectName("bn_booking")
        self.horizontalLayout_16.addWidget(self.bn_booking)
        self.verticalLayout_3.addWidget(self.frame_booking)
        self.frame_schedule = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_schedule.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_schedule.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_schedule.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_schedule.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_schedule.setObjectName("frame_schedule")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_schedule)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.bn_schedule = QtWidgets.QPushButton(self.frame_schedule)
        self.bn_schedule.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_schedule.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_schedule.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_schedule.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("exe/icons/1x/schedule-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_schedule.setIcon(icon6)
        self.bn_schedule.setFlat(True)
        self.bn_schedule.setObjectName("bn_schedule")
        self.horizontalLayout_17.addWidget(self.bn_schedule)
        self.verticalLayout_3.addWidget(self.frame_schedule)
        self.frame_android = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_android.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_android.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_android.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android.setObjectName("frame_android")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_android)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bn_android = QtWidgets.QPushButton(self.frame_android)
        self.bn_android.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_android.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_android.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/androidAsset 49.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android.setIcon(icon7)
        self.bn_android.setIconSize(QtCore.QSize(20, 22))
        self.bn_android.setFlat(True)
        self.bn_android.setObjectName("bn_android")
        self.horizontalLayout_18.addWidget(self.bn_android)
        self.verticalLayout_3.addWidget(self.frame_android)
        self.frame_8 = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_bottom_west)
        self.frame_bottom_east = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_east.setObjectName("frame_bottom_east")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_bottom_east)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setMinimumSize(QtCore.QSize(16777214, 50))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setStyleSheet("background:rgb(91,90,90);")
        self.page_home.setObjectName("page_home")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.page_home)
        self.horizontalLayout_19.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_home_main = QtWidgets.QFrame(self.page_home)
        self.frame_home_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home_main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_home_main.setObjectName("frame_home_main")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_home_main)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lab_home_main_hed = QtWidgets.QLabel(self.frame_home_main)
        self.lab_home_main_hed.setMinimumSize(QtCore.QSize(0, 55))
        self.lab_home_main_hed.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.lab_home_main_hed.setFont(font)
        self.lab_home_main_hed.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.lab_home_main_hed.setTextFormat(QtCore.Qt.RichText)
        self.lab_home_main_hed.setObjectName("lab_home_main_hed")
        self.verticalLayout_5.addWidget(self.lab_home_main_hed)
        self.lab_home_main_disc = QtWidgets.QLabel(self.frame_home_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lab_home_main_disc.setFont(font)
        self.lab_home_main_disc.setStyleSheet("color:rgb(255,255,255);")
        self.lab_home_main_disc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lab_home_main_disc.setWordWrap(True)
        self.lab_home_main_disc.setObjectName("lab_home_main_disc")
        self.verticalLayout_5.addWidget(self.lab_home_main_disc)
        self.horizontalLayout_19.addWidget(self.frame_home_main)
        self.vert_divide = QtWidgets.QFrame(self.page_home)
        self.vert_divide.setFrameShape(QtWidgets.QFrame.VLine)
        self.vert_divide.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vert_divide.setObjectName("vert_divide")
        self.horizontalLayout_19.addWidget(self.vert_divide)
        self.frame_home_stat = QtWidgets.QFrame(self.page_home)
        self.frame_home_stat.setMinimumSize(QtCore.QSize(220, 0))
        self.frame_home_stat.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_home_stat.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home_stat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_home_stat.setObjectName("frame_home_stat")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_home_stat)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lab_home_stat_hed = QtWidgets.QLabel(self.frame_home_stat)
        self.lab_home_stat_hed.setMinimumSize(QtCore.QSize(0, 55))
        self.lab_home_stat_hed.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.lab_home_stat_hed.setFont(font)
        self.lab_home_stat_hed.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.lab_home_stat_hed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_home_stat_hed.setObjectName("lab_home_stat_hed")
        self.verticalLayout_6.addWidget(self.lab_home_stat_hed)
        self.clock_fram = QtWidgets.QFrame(self.frame_home_stat)
        self.clock_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clock_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clock_fram.setObjectName("clock_fram")
        self.verticalLayout_6.addWidget(self.clock_fram)
        self.lab_home_stat_disc = QtWidgets.QLabel(self.frame_home_stat)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lab_home_stat_disc.setFont(font)
        self.lab_home_stat_disc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lab_home_stat_disc.setObjectName("lab_home_stat_disc")
        self.verticalLayout_6.addWidget(self.lab_home_stat_disc)
        self.horizontalLayout_19.addWidget(self.frame_home_stat)
        self.stackedWidget.addWidget(self.page_home)
        self.page_about_home = QtWidgets.QWidget()
        self.page_about_home.setStyleSheet("background:rgb(91,90,90);")
        self.page_about_home.setObjectName("page_about_home")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_about_home)
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lab_about_home = QtWidgets.QLabel(self.page_about_home)
        self.lab_about_home.setMinimumSize(QtCore.QSize(0, 55))
        self.lab_about_home.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.lab_about_home.setFont(font)
        self.lab_about_home.setStyleSheet("color:rgb(255,255,255);")
        self.lab_about_home.setObjectName("lab_about_home")
        self.verticalLayout_13.addWidget(self.lab_about_home)
        self.frame_about_home = QtWidgets.QFrame(self.page_about_home)
        self.frame_about_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_about_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_about_home.setObjectName("frame_about_home")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_about_home)
        self.horizontalLayout_28.setContentsMargins(5, 5, 0, 5)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.text_about_home = QtWidgets.QTextEdit(self.frame_about_home)
        self.text_about_home.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.text_about_home.setFont(font)
        self.text_about_home.setStyleSheet("color:rgb(255,255,255);")
        self.text_about_home.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_about_home.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_about_home.setReadOnly(True)
        self.text_about_home.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.text_about_home.setObjectName("text_about_home")
        self.horizontalLayout_28.addWidget(self.text_about_home)
        self.vsb_about_home = QtWidgets.QScrollBar(self.frame_about_home)
        self.vsb_about_home.setStyleSheet("QScrollBar:vertical {\n"
"    background:rgb(51,51,51);\n"
"    width:20px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background:rgb(0,143,170);\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"     background:rgb(51,51,51);\n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"     background:rgb(51,51,51);\n"
"}")
        self.vsb_about_home.setOrientation(QtCore.Qt.Vertical)
        self.vsb_about_home.setObjectName("vsb_about_home")
        self.horizontalLayout_28.addWidget(self.vsb_about_home)
        self.verticalLayout_13.addWidget(self.frame_about_home)
        self.stackedWidget.addWidget(self.page_about_home)
        self.page_about_cloud = QtWidgets.QWidget()
        self.page_about_cloud.setStyleSheet("background:rgb(91,90,90);")
        self.page_about_cloud.setObjectName("page_about_cloud")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.page_about_cloud)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_10 = QtWidgets.QLabel(self.page_about_cloud)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255,255,255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_29.addWidget(self.label_10)
        self.stackedWidget.addWidget(self.page_about_cloud)
        self.page_about_android = QtWidgets.QWidget()
        self.page_about_android.setStyleSheet("background:rgb(91,90,90);")
        self.page_about_android.setObjectName("page_about_android")
        self.stackedWidget.addWidget(self.page_about_android)
        self.page_about_booking = QtWidgets.QWidget()
        self.page_about_booking.setStyleSheet("background:rgb(91,90,90);")
        self.page_about_booking.setObjectName("page_about_booking")
        self.stackedWidget.addWidget(self.page_about_booking)
        self.page_booking = QtWidgets.QWidget()
        self.page_booking.setStyleSheet("background:rgb(91,90,90);")
        self.page_booking.setObjectName("page_booking")
        self.lab_Bug = QtWidgets.QLabel(self.page_booking)
        self.lab_Bug.setGeometry(QtCore.QRect(12, 12, 400, 55))
        self.lab_Bug.setMinimumSize(QtCore.QSize(1, 55))
        self.lab_Bug.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.lab_Bug.setFont(font)
        self.lab_Bug.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lab_Bug.setStyleSheet("color:rgb(255,255,255);")
        self.lab_Bug.setObjectName("lab_Bug")
        self.widget = QtWidgets.QWidget(self.page_booking)
        self.widget.setGeometry(QtCore.QRect(11, 71, 16777214, 10591))
        self.widget.setMinimumSize(QtCore.QSize(1, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:50px;")
        self.widget.setObjectName("widget")
        self.pushButton_ConfirmBooking = QtWidgets.QPushButton(self.widget)
        self.pushButton_ConfirmBooking.setGeometry(QtCore.QRect(460, 340, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton_ConfirmBooking.setFont(font)
        self.pushButton_ConfirmBooking.setStyleSheet("border-radius:15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.pushButton_ConfirmBooking.setObjectName("pushButton_ConfirmBooking")
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_5.setGeometry(QtCore.QRect(410, 270, 371, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setItalic(True)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.radioButton_5.setObjectName("radioButton_5")
        self.start_Location = QtWidgets.QComboBox(self.widget)
        self.start_Location.setGeometry(QtCore.QRect(300, 110, 151, 31))
        self.start_Location.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_Location.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.start_Location.setObjectName("start_Location")
        self.date_of_Travel = QtWidgets.QDateEdit(self.widget)
        self.date_of_Travel.setGeometry(QtCore.QRect(660, 210, 161, 31))
        self.date_of_Travel.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.date_of_Travel.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2070, 12, 31), QtCore.QTime(23, 59, 59)))
        self.date_of_Travel.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 12, 16), QtCore.QTime(0, 0, 0)))
        self.date_of_Travel.setObjectName("date_of_Travel")
        self.end_Location = QtWidgets.QComboBox(self.widget)
        self.end_Location.setGeometry(QtCore.QRect(660, 110, 161, 31))
        self.end_Location.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.end_Location.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.end_Location.setObjectName("end_Location")
        self.label_16 = QtWidgets.QLabel(self.page_booking)
        self.label_16.setGeometry(QtCore.QRect(180, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.comboBox_TicketType = QtWidgets.QComboBox(self.page_booking)
        self.comboBox_TicketType.setGeometry(QtCore.QRect(310, 230, 151, 31))
        self.comboBox_TicketType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_TicketType.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_TicketType.setObjectName("comboBox_TicketType")
        self.comboBox_TicketType.addItem("")
        self.comboBox_TicketType.addItem("")
        self.comboBox_TicketType.addItem("")
        self.label_14 = QtWidgets.QLabel(self.page_booking)
        self.label_14.setGeometry(QtCore.QRect(190, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_22 = QtWidgets.QLabel(self.page_booking)
        self.label_22.setGeometry(QtCore.QRect(520, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_12 = QtWidgets.QLabel(self.page_booking)
        self.label_12.setGeometry(QtCore.QRect(181, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.page_booking)
        self.label_11.setGeometry(QtCore.QRect(380, 90, 331, 48))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel#label_11{\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px\n"
"\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_18 = QtWidgets.QLabel(self.page_booking)
        self.label_18.setGeometry(QtCore.QRect(510, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.page_booking)
        self.label_21.setGeometry(QtCore.QRect(530, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_Amount = QtWidgets.QLabel(self.page_booking)
        self.label_Amount.setEnabled(False)
        self.label_Amount.setGeometry(QtCore.QRect(670, 230, 161, 31))
        self.label_Amount.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_Amount.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_Amount.setText("")
        self.label_Amount.setTextFormat(QtCore.Qt.PlainText)
        self.label_Amount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Amount.setObjectName("label_Amount")
        self.comboBox_TicketCount = QtWidgets.QComboBox(self.page_booking)
        self.comboBox_TicketCount.setGeometry(QtCore.QRect(310, 280, 151, 31))
        self.comboBox_TicketCount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_TicketCount.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_TicketCount.setObjectName("comboBox_TicketCount")
        self.comboBox_TicketCount.addItem("")
        self.comboBox_TicketCount.addItem("")
        self.comboBox_TicketCount.addItem("")
        self.comboBox_TicketCount.addItem("")
        self.comboBox_TicketCount.addItem("")
        self.comboBox_TicketCount.addItem("")
        self.widget.raise_()
        self.lab_Bug.raise_()
        self.label_18.raise_()
        self.label_21.raise_()
        self.label_14.raise_()
        self.label_16.raise_()
        self.comboBox_TicketCount.raise_()
        self.label_22.raise_()
        self.comboBox_TicketType.raise_()
        self.label_Amount.raise_()
        self.label_12.raise_()
        self.label_11.raise_()
        self.stackedWidget.addWidget(self.page_booking)
        self.page_cloud = QtWidgets.QWidget()
        self.page_cloud.setStyleSheet("background:rgb(91,90,90);")
        self.page_cloud.setObjectName("page_cloud")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_cloud)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lab_cloud_main = QtWidgets.QLabel(self.page_cloud)
        self.lab_cloud_main.setMinimumSize(QtCore.QSize(0, 55))
        self.lab_cloud_main.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.lab_cloud_main.setFont(font)
        self.lab_cloud_main.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.lab_cloud_main.setObjectName("lab_cloud_main")
        self.verticalLayout_8.addWidget(self.lab_cloud_main)
        self.frame_2 = QtWidgets.QFrame(self.page_cloud)
        self.frame_2.setEnabled(True)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 235))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 235))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255,255,255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255,255,255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255,255,255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.line_cloud_proxy = QtWidgets.QLineEdit(self.frame_2)
        self.line_cloud_proxy.setMinimumSize(QtCore.QSize(400, 25))
        self.line_cloud_proxy.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_cloud_proxy.setFont(font)
        self.line_cloud_proxy.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_cloud_proxy.setObjectName("line_cloud_proxy")
        self.gridLayout_2.addWidget(self.line_cloud_proxy, 2, 1, 1, 3)
        self.line_cloud_id = QtWidgets.QLineEdit(self.frame_2)
        self.line_cloud_id.setEnabled(True)
        self.line_cloud_id.setMinimumSize(QtCore.QSize(400, 25))
        self.line_cloud_id.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_cloud_id.setFont(font)
        self.line_cloud_id.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_cloud_id.setObjectName("line_cloud_id")
        self.gridLayout_2.addWidget(self.line_cloud_id, 0, 1, 1, 3)
        self.line_cloud_adress = QtWidgets.QLineEdit(self.frame_2)
        self.line_cloud_adress.setMinimumSize(QtCore.QSize(400, 25))
        self.line_cloud_adress.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_cloud_adress.setFont(font)
        self.line_cloud_adress.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_cloud_adress.setObjectName("line_cloud_adress")
        self.gridLayout_2.addWidget(self.line_cloud_adress, 1, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 2)
        self.bn_cloud_clear = QtWidgets.QPushButton(self.frame_2)
        self.bn_cloud_clear.setEnabled(True)
        self.bn_cloud_clear.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_cloud_clear.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_cloud_clear.setFont(font)
        self.bn_cloud_clear.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_cloud_clear.setObjectName("bn_cloud_clear")
        self.gridLayout_2.addWidget(self.bn_cloud_clear, 3, 2, 1, 1)
        self.bn_cloud_connect = QtWidgets.QPushButton(self.frame_2)
        self.bn_cloud_connect.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_cloud_connect.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_cloud_connect.setFont(font)
        self.bn_cloud_connect.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_cloud_connect.setObjectName("bn_cloud_connect")
        self.gridLayout_2.addWidget(self.bn_cloud_connect, 3, 3, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 162, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_cloud)
        self.page_android = QtWidgets.QWidget()
        self.page_android.setStyleSheet("background:rgb(91,90,90);")
        self.page_android.setObjectName("page_android")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_android)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_android_menu = QtWidgets.QFrame(self.page_android)
        self.frame_android_menu.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_android_menu.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_android_menu.setStyleSheet("background:rgb(51,51,51);")
        self.frame_android_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_menu.setObjectName("frame_android_menu")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_android_menu)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_android_contact = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_contact.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_contact.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_contact.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_contact.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_contact.setObjectName("frame_android_contact")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_android_contact)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.bn_android_contact = QtWidgets.QPushButton(self.frame_android_contact)
        self.bn_android_contact.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_contact.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_contact.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_contact.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/bookAsset 57.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_contact.setIcon(icon8)
        self.bn_android_contact.setIconSize(QtCore.QSize(13, 16))
        self.bn_android_contact.setFlat(True)
        self.bn_android_contact.setObjectName("bn_android_contact")
        self.horizontalLayout_21.addWidget(self.bn_android_contact)
        self.horizontalLayout_20.addWidget(self.frame_android_contact)
        self.frame_android_game = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_game.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_game.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_game.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_game.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_game.setObjectName("frame_android_game")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_android_game)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.bn_android_game = QtWidgets.QPushButton(self.frame_android_game)
        self.bn_android_game.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_game.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_game.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_game.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/gameAsset 61.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_game.setIcon(icon9)
        self.bn_android_game.setIconSize(QtCore.QSize(20, 13))
        self.bn_android_game.setFlat(True)
        self.bn_android_game.setObjectName("bn_android_game")
        self.horizontalLayout_22.addWidget(self.bn_android_game)
        self.horizontalLayout_20.addWidget(self.frame_android_game)
        self.frame_android_clean = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_clean.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_clean.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_clean.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_clean.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_clean.setObjectName("frame_android_clean")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_android_clean)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bn_android_clean = QtWidgets.QPushButton(self.frame_android_clean)
        self.bn_android_clean.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_clean.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_clean.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_clean.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/cleanAsset 59.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_clean.setIcon(icon10)
        self.bn_android_clean.setFlat(True)
        self.bn_android_clean.setObjectName("bn_android_clean")
        self.horizontalLayout_23.addWidget(self.bn_android_clean)
        self.horizontalLayout_20.addWidget(self.frame_android_clean)
        self.frame_android_world = QtWidgets.QFrame(self.frame_android_menu)
        self.frame_android_world.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_android_world.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_android_world.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_world.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_world.setObjectName("frame_android_world")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_android_world)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.bn_android_world = QtWidgets.QPushButton(self.frame_android_world)
        self.bn_android_world.setMinimumSize(QtCore.QSize(80, 30))
        self.bn_android_world.setMaximumSize(QtCore.QSize(80, 30))
        self.bn_android_world.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_android_world.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/worldAsset 60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_android_world.setIcon(icon11)
        self.bn_android_world.setFlat(True)
        self.bn_android_world.setObjectName("bn_android_world")
        self.horizontalLayout_24.addWidget(self.bn_android_world)
        self.horizontalLayout_20.addWidget(self.frame_android_world)
        spacerItem3 = QtWidgets.QSpacerItem(397, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_9.addWidget(self.frame_android_menu)
        self.stackedWidget_android = QtWidgets.QStackedWidget(self.page_android)
        self.stackedWidget_android.setStyleSheet("background:rgb(91,90,90);")
        self.stackedWidget_android.setObjectName("stackedWidget_android")
        self.page_android_contact = QtWidgets.QWidget()
        self.page_android_contact.setStyleSheet("background:rgb(91,90,90);")
        self.page_android_contact.setObjectName("page_android_contact")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_android_contact)
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lab_android_contact = QtWidgets.QLabel(self.page_android_contact)
        self.lab_android_contact.setMinimumSize(QtCore.QSize(0, 55))
        self.lab_android_contact.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.lab_android_contact.setFont(font)
        self.lab_android_contact.setStyleSheet("color:rgb(255,255,255);")
        self.lab_android_contact.setObjectName("lab_android_contact")
        self.verticalLayout_10.addWidget(self.lab_android_contact)
        self.frame_android_bottom = QtWidgets.QFrame(self.page_android_contact)
        self.frame_android_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_bottom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_bottom.setObjectName("frame_android_bottom")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_android_bottom)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lab_person_icon = QtWidgets.QLabel(self.frame_android_bottom)
        self.lab_person_icon.setMinimumSize(QtCore.QSize(200, 160))
        self.lab_person_icon.setMaximumSize(QtCore.QSize(200, 160))
        self.lab_person_icon.setText("")
        self.lab_person_icon.setPixmap(QtGui.QPixmap("../Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/peopleAsset 62.png"))
        self.lab_person_icon.setObjectName("lab_person_icon")
        self.gridLayout_3.addWidget(self.lab_person_icon, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.frame_android_field = QtWidgets.QFrame(self.frame_android_bottom)
        self.frame_android_field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_android_field.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_android_field.setObjectName("frame_android_field")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_android_field)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame_android_field)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255,255,255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_android_field)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(255,255,255);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_android_field)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255,255,255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_android_field)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255);")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 3)
        self.line_android_name = QtWidgets.QLineEdit(self.frame_android_field)
        self.line_android_name.setEnabled(False)
        self.line_android_name.setMinimumSize(QtCore.QSize(300, 25))
        self.line_android_name.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_android_name.setFont(font)
        self.line_android_name.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_android_name.setObjectName("line_android_name")
        self.gridLayout_4.addWidget(self.line_android_name, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_android_field)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255,255,255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 3)
        self.line_android_org = QtWidgets.QLineEdit(self.frame_android_field)
        self.line_android_org.setEnabled(False)
        self.line_android_org.setMinimumSize(QtCore.QSize(300, 25))
        self.line_android_org.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_android_org.setFont(font)
        self.line_android_org.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_android_org.setObjectName("line_android_org")
        self.gridLayout_4.addWidget(self.line_android_org, 4, 3, 1, 1)
        self.line_android_adress = QtWidgets.QLineEdit(self.frame_android_field)
        self.line_android_adress.setEnabled(False)
        self.line_android_adress.setMinimumSize(QtCore.QSize(300, 25))
        self.line_android_adress.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_android_adress.setFont(font)
        self.line_android_adress.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_android_adress.setObjectName("line_android_adress")
        self.gridLayout_4.addWidget(self.line_android_adress, 3, 3, 1, 1)
        self.line_android_ph = QtWidgets.QLineEdit(self.frame_android_field)
        self.line_android_ph.setEnabled(False)
        self.line_android_ph.setMinimumSize(QtCore.QSize(300, 25))
        self.line_android_ph.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_android_ph.setFont(font)
        self.line_android_ph.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_android_ph.setObjectName("line_android_ph")
        self.gridLayout_4.addWidget(self.line_android_ph, 7, 3, 1, 1)
        self.line_android_email = QtWidgets.QLineEdit(self.frame_android_field)
        self.line_android_email.setEnabled(False)
        self.line_android_email.setMinimumSize(QtCore.QSize(300, 25))
        self.line_android_email.setMaximumSize(QtCore.QSize(400, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.line_android_email.setFont(font)
        self.line_android_email.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.line_android_email.setObjectName("line_android_email")
        self.gridLayout_4.addWidget(self.line_android_email, 5, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 8, 8, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 4, 8, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 9, 3, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_android_field)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_25.setContentsMargins(100, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.bn_android_contact_edit = QtWidgets.QPushButton(self.frame_3)
        self.bn_android_contact_edit.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_edit.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_edit.setFont(font)
        self.bn_android_contact_edit.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_edit.setObjectName("bn_android_contact_edit")
        self.horizontalLayout_25.addWidget(self.bn_android_contact_edit)
        self.bn_android_contact_share = QtWidgets.QPushButton(self.frame_3)
        self.bn_android_contact_share.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_share.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_share.setFont(font)
        self.bn_android_contact_share.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_share.setObjectName("bn_android_contact_share")
        self.horizontalLayout_25.addWidget(self.bn_android_contact_share)
        self.bn_android_contact_delete = QtWidgets.QPushButton(self.frame_3)
        self.bn_android_contact_delete.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_delete.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_delete.setFont(font)
        self.bn_android_contact_delete.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(112,0,0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(112,0,0);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_delete.setObjectName("bn_android_contact_delete")
        self.horizontalLayout_25.addWidget(self.bn_android_contact_delete)
        self.bn_android_contact_save = QtWidgets.QPushButton(self.frame_3)
        self.bn_android_contact_save.setEnabled(False)
        self.bn_android_contact_save.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_android_contact_save.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_android_contact_save.setFont(font)
        self.bn_android_contact_save.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.bn_android_contact_save.setObjectName("bn_android_contact_save")
        self.horizontalLayout_25.addWidget(self.bn_android_contact_save)
        self.gridLayout_4.addWidget(self.frame_3, 8, 0, 1, 7)
        self.gridLayout_3.addWidget(self.frame_android_field, 0, 1, 2, 1)
        self.verticalLayout_10.addWidget(self.frame_android_bottom)
        self.stackedWidget_android.addWidget(self.page_android_contact)
        self.page_android_game = QtWidgets.QWidget()
        self.page_android_game.setStyleSheet("background:rgb(91,90,90);")
        self.page_android_game.setObjectName("page_android_game")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_android_game)
        self.verticalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lab_gamepad = QtWidgets.QLabel(self.page_android_game)
        self.lab_gamepad.setMinimumSize(QtCore.QSize(0, 55))
        self.lab_gamepad.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.lab_gamepad.setFont(font)
        self.lab_gamepad.setStyleSheet("color:rgb(255,255,255);")
        self.lab_gamepad.setObjectName("lab_gamepad")
        self.verticalLayout_11.addWidget(self.lab_gamepad)
        self.frame_textbar = QtWidgets.QFrame(self.page_android_game)
        self.frame_textbar.setStyleSheet("background:rgb(91,90,90);")
        self.frame_textbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_textbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_textbar.setObjectName("frame_textbar")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_textbar)
        self.horizontalLayout_26.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.textEdit_gamepad = QtWidgets.QTextEdit(self.frame_textbar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.textEdit_gamepad.setFont(font)
        self.textEdit_gamepad.setStyleSheet("color:rgb(255,255,255);")
        self.textEdit_gamepad.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_gamepad.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_gamepad.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_gamepad.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_gamepad.setObjectName("textEdit_gamepad")
        self.horizontalLayout_26.addWidget(self.textEdit_gamepad)
        self.vsb_gamepad = QtWidgets.QScrollBar(self.frame_textbar)
        self.vsb_gamepad.setStyleSheet("QScrollBar:vertical {\n"
"    background:rgb(51,51,51);\n"
"    width:20px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background:rgb(0,143,170);\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"     background:rgb(51,51,51);\n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"     background:rgb(51,51,51);\n"
"}")
        self.vsb_gamepad.setOrientation(QtCore.Qt.Vertical)
        self.vsb_gamepad.setInvertedControls(True)
        self.vsb_gamepad.setObjectName("vsb_gamepad")
        self.horizontalLayout_26.addWidget(self.vsb_gamepad)
        self.verticalLayout_11.addWidget(self.frame_textbar)
        self.stackedWidget_android.addWidget(self.page_android_game)
        self.page_android_clean = QtWidgets.QWidget()
        self.page_android_clean.setStyleSheet("background:rgb(91,90,90);")
        self.page_android_clean.setObjectName("page_android_clean")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_android_clean)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 5, 1, 1)
        self.groupBox_clean = QtWidgets.QGroupBox(self.page_android_clean)
        self.groupBox_clean.setMinimumSize(QtCore.QSize(250, 300))
        self.groupBox_clean.setMaximumSize(QtCore.QSize(250, 300))
        self.groupBox_clean.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.groupBox_clean.setFont(font)
        self.groupBox_clean.setStyleSheet("QGroupBox{\n"
"    border:1px solid rgb(51,51,51);    \n"
"    border-radius:4px;\n"
"    color:white;\n"
"    background:rgb(91,90,90);\n"
"}\n"
"")
        self.groupBox_clean.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_clean.setFlat(False)
        self.groupBox_clean.setCheckable(False)
        self.groupBox_clean.setObjectName("groupBox_clean")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_clean)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    background:rgb(91,90,90);\n"
"    color:white;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:10px;\n"
"    height:10px;\n"
"    border-radius: 7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:rgb(91,90,90);\n"
"    border:2px solid rgb(51,51,51);\n"
"}")
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_12.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"    background:rgb(91,90,90);\n"
"    color:white;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:10px;\n"
"    height:10px;\n"
"    border-radius: 7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:rgb(91,90,90);\n"
"    border:2px solid rgb(51,51,51);\n"
"}")
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_12.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("QRadioButton {\n"
"    background:rgb(91,90,90);\n"
"    color:white;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:10px;\n"
"    height:10px;\n"
"    border-radius: 7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:rgb(91,90,90);\n"
"    border:2px solid rgb(51,51,51);\n"
"}")
        self.radioButton_3.setAutoExclusive(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_12.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("QRadioButton {\n"
"    background:rgb(91,90,90);\n"
"    color:white;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width:10px;\n"
"    height:10px;\n"
"    border-radius: 7px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:rgb(91,90,90);\n"
"    border:2px solid rgb(51,51,51);\n"
"}")
        self.radioButton_4.setAutoExclusive(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_12.addWidget(self.radioButton_4)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_12.addWidget(self.checkBox)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("QCheckBox {\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"")
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_12.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_12.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_clean)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,170);\n"
"    border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_12.addWidget(self.checkBox_3)
        self.gridLayout_5.addWidget(self.groupBox_clean, 0, 0, 1, 1)
        self.lab_clean = QtWidgets.QLabel(self.page_android_clean)
        self.lab_clean.setStyleSheet("")
        self.lab_clean.setText("")
        self.lab_clean.setObjectName("lab_clean")
        self.gridLayout_5.addWidget(self.lab_clean, 0, 1, 2, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 2, 0, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.page_android_clean)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 300))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border:1px solid rgb(51,51,51);    \n"
"    border-radius:4px;\n"
"    color:white;\n"
"    background:rgb(91,90,90);\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_2.setStyleSheet("QSlider::groove:horizontal {\n"
"    height:5px;\n"
"    background: rgb(51,51,51);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background:rgb(0,143,170);\n"
"    width: 10px;\n"
"margin:-8px 0\n"
"}\n"
"\n"
"QSlider::add-page:horizondal {\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QSlider::sub-page:horizondal {\n"
"    background:rgb(51,51,51);\n"
"}")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_6.addWidget(self.horizontalSlider_2, 0, 0, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider.setStyleSheet("QSlider::groove:vertical {\n"
"    background: red;\n"
"    width:5px\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"    background:rgb(0,143,170);\n"
"    margin:0 -8px\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background:rgb(51,51,51);\n"
"}")
        self.verticalSlider.setTracking(True)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout_6.addWidget(self.verticalSlider, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 3, 1, 1)
        self.stackedWidget_android.addWidget(self.page_android_clean)
        self.page_android_world = QtWidgets.QWidget()
        self.page_android_world.setStyleSheet("background:rgb(91,90,90);")
        self.page_android_world.setObjectName("page_android_world")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.page_android_world)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_9 = QtWidgets.QLabel(self.page_android_world)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(30)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255,255,255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_27.addWidget(self.label_9)
        self.stackedWidget_android.addWidget(self.page_android_world)
        self.verticalLayout_9.addWidget(self.stackedWidget_android)
        self.stackedWidget.addWidget(self.page_android)
        self.horizontalLayout_14.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_low = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame_low.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_low.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_low.setStyleSheet("")
        self.frame_low.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_low.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_low.setObjectName("frame_low")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_low)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_tab = QtWidgets.QFrame(self.frame_low)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_tab.setFont(font)
        self.frame_tab.setStyleSheet("background:rgb(51,51,51);")
        self.frame_tab.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_tab.setObjectName("frame_tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_tab)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lab_tab = QtWidgets.QLabel(self.frame_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        self.lab_tab.setFont(font)
        self.lab_tab.setStyleSheet("color:rgb(255,255,255);")
        self.lab_tab.setObjectName("lab_tab")
        self.horizontalLayout_12.addWidget(self.lab_tab)
        self.horizontalLayout_11.addWidget(self.frame_tab)
        self.frame_drag = QtWidgets.QFrame(self.frame_low)
        self.frame_drag.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_drag.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_drag.setStyleSheet("background:rgb(51,51,51);")
        self.frame_drag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_drag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_drag.setObjectName("frame_drag")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_drag)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_11.addWidget(self.frame_drag)
        self.verticalLayout_2.addWidget(self.frame_low)
        self.horizontalLayout_2.addWidget(self.frame_bottom_east)
        self.verticalLayout.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.stackedWidget_android.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_appname.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lab_user.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">User8455</span></p></body></html>"))
        self.bn_min.setToolTip(_translate("MainWindow", "Minimize"))
        self.bn_max.setToolTip(_translate("MainWindow", "Maximize"))
        self.bn_close.setToolTip(_translate("MainWindow", "Close"))
        self.bn_home.setToolTip(_translate("MainWindow", "Home"))
        self.bn_booking.setToolTip(_translate("MainWindow", "Booking"))
        self.bn_schedule.setToolTip(_translate("MainWindow", "Schedule"))
        self.bn_android.setToolTip(_translate("MainWindow", "Android"))
        self.lab_home_main_hed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Welcome to Railway Analysis</span></p></body></html>"))
        self.lab_home_main_disc.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Effortless Railway Management at Your Fingertips</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• Discover and book train tickets with just a few taps. Effortlessly plan your travel from the convenience of your device.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• Stay on top of train schedules with real-time updates on upcoming departures and arrivals. Your journey, your schedule.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• Unlock special promotions and deals to make your travel experience even more delightful. Check out our featured offers now!</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• Your security is our priority. Rest assured that your data is protected with state-of-the-art security measures.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• Available on all devices – whether you\'re on your smartphone, tablet, or desktop. Your railway experience, your way.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">• Our dedicated customer support team is ready to assist you. Contact us anytime via chat, helpline, or email.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Making railway travel hassle-free, one journey at a time.</span></p></body></html>"))
        self.lab_home_stat_hed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Time</span></p></body></html>"))
        self.lab_home_stat_disc.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lab_about_home.setText(_translate("MainWindow", "About: Home"))
        self.label_10.setText(_translate("MainWindow", "Empty"))
        self.lab_Bug.setToolTip(_translate("MainWindow", "Schedule"))
        self.lab_Bug.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">Booking</span></p></body></html>"))
        self.pushButton_ConfirmBooking.setText(_translate("MainWindow", "Confirm Booking"))
        self.radioButton_5.setText(_translate("MainWindow", "I except all the terms and conditions"))
        self.label_16.setText(_translate("MainWindow", "Ticket Count:"))
        self.comboBox_TicketType.setItemText(0, _translate("MainWindow", "Basic"))
        self.comboBox_TicketType.setItemText(1, _translate("MainWindow", "Standard"))
        self.comboBox_TicketType.setItemText(2, _translate("MainWindow", "Premium"))
        self.label_14.setText(_translate("MainWindow", "Ticket Type:"))
        self.label_22.setText(_translate("MainWindow", "Date of Traval:"))
        self.label_12.setText(_translate("MainWindow", "Start Location:"))
        self.label_11.setText(_translate("MainWindow", "Book Now!"))
        self.label_18.setText(_translate("MainWindow", "End Location:"))
        self.label_21.setText(_translate("MainWindow", "Amount:"))
        self.comboBox_TicketCount.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_TicketCount.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_TicketCount.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_TicketCount.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_TicketCount.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_TicketCount.setItemText(5, _translate("MainWindow", "6"))
        self.lab_cloud_main.setText(_translate("MainWindow", "Cloud Connect"))
        self.label_2.setText(_translate("MainWindow", "Client ID :"))
        self.label_3.setText(_translate("MainWindow", "Server Adress :"))
        self.label_4.setText(_translate("MainWindow", "Proxy :"))
        self.bn_cloud_clear.setText(_translate("MainWindow", "Clear"))
        self.bn_cloud_connect.setText(_translate("MainWindow", "Connect"))
        self.bn_android_contact.setToolTip(_translate("MainWindow", "Contact"))
        self.bn_android_game.setToolTip(_translate("MainWindow", "GamePad"))
        self.bn_android_clean.setToolTip(_translate("MainWindow", "Clean"))
        self.bn_android_world.setToolTip(_translate("MainWindow", "World"))
        self.lab_android_contact.setText(_translate("MainWindow", "Contact"))
        self.label_8.setText(_translate("MainWindow", "Ph:"))
        self.label_6.setText(_translate("MainWindow", "Organisation:"))
        self.label_7.setText(_translate("MainWindow", "Email:"))
        self.label.setText(_translate("MainWindow", "Name: "))
        self.line_android_name.setText(_translate("MainWindow", "ALBERT EINSTEIN"))
        self.label_5.setText(_translate("MainWindow", "Adress: "))
        self.line_android_org.setText(_translate("MainWindow", "Physist"))
        self.line_android_adress.setText(_translate("MainWindow", "112 Mercer Street"))
        self.line_android_email.setText(_translate("MainWindow", "einstein@gmail.com"))
        self.bn_android_contact_edit.setText(_translate("MainWindow", "Edit"))
        self.bn_android_contact_share.setText(_translate("MainWindow", "Share"))
        self.bn_android_contact_delete.setText(_translate("MainWindow", "Delete"))
        self.bn_android_contact_save.setText(_translate("MainWindow", "Save"))
        self.lab_gamepad.setText(_translate("MainWindow", "GamePad"))
        self.groupBox_clean.setTitle(_translate("MainWindow", "Review"))
        self.radioButton.setText(_translate("MainWindow", "Clean History"))
        self.radioButton_2.setText(_translate("MainWindow", "Clean Password"))
        self.radioButton_3.setText(_translate("MainWindow", "Clean Chache"))
        self.radioButton_4.setText(_translate("MainWindow", "Clean Bookmarks"))
        self.checkBox.setText(_translate("MainWindow", "Did you liked the UI"))
        self.checkBox_4.setText(_translate("MainWindow", "Did you like the Color Scheme"))
        self.checkBox_2.setText(_translate("MainWindow", "Did you like Custome Buttons"))
        self.checkBox_3.setText(_translate("MainWindow", "Did you like the Stacked Window"))
        self.groupBox.setTitle(_translate("MainWindow", "Sliders"))
        self.label_9.setText(_translate("MainWindow", "VACANT? TRY YOUR IMAGINATION"))
        self.lab_tab.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.frame_drag.setToolTip(_translate("MainWindow", "Drag"))
